/* MindHarbor: working LOCAL booking workflow for fictional experts. No real clinical appointments. */
(()=>{'use strict';
const KEY='mindharbor-booking-v2';
const experts=[
 {name:'นพ. ธนวัฒน์ ศรีวรรณ',role:'จิตแพทย์ (สมมติ)',days:[1,3,5],hours:['09:00','10:00','11:00','14:00'],duration:50,fee:1800,img:'assets/psychiatrist.png'},
 {name:'ดร. กมลวรรณ จันทร์เพ็ญ',role:'นักจิตวิทยาคลินิก (สมมติ)',days:[2,4,6],hours:['10:00','11:00','13:00','15:00'],duration:50,fee:1200,img:'assets/psychologist.png'},
 {name:'คุณธีรดา เมธากุล',role:'ผู้เชี่ยวชาญสุขภาวะองค์กร (สมมติ)',days:[1,2,4,5],hours:['09:00','11:00','13:00','16:00'],duration:60,fee:1500,img:'assets/wellbeing.png'},
 {name:'คุณเอกณรงค์ พัฒนกิจ',role:'นักจิตวิทยาการปรึกษา (สมมติ)',days:[1,3,4,6],hours:['09:00','10:00','14:00','15:00'],duration:50,fee:1100,img:'assets/counselor.png'}
];
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDay=d=>{const x=new Date(d+'T12:00:00');return Number.isNaN(x.getTime())?-1:x.getDay()};
const localToday=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const plusDays=n=>{const d=new Date();d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
let records=[];try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(x))records=x}catch{}
const save=()=>localStorage.setItem(KEY,JSON.stringify(records));
const getExpert=()=>experts.find(e=>e.name===$('expertSelect').value)||experts[0];
const busy=(date,time,expert)=>records.some(r=>r.date===date&&r.time===time&&r.expert===expert&&r.status!=='ยกเลิก');
const modal=(title,html)=>{$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modal').classList.add('show')};
const selectedTime=()=>document.querySelector('#slots .slot.selected:not(:disabled)')?.dataset.time;
function refresh(){const e=getExpert(),date=$('date').value,valid=date>=localToday()&&date<=plusDays(60)&&e.days.includes(localDay(date));$('expertSummary').innerHTML=`<img src="${e.img}" alt="ภาพสมมติ"/><div><strong>${esc(e.name)}</strong><br><small>${esc(e.role)} · ${e.duration} นาที · ${e.fee.toLocaleString('th-TH')} บาท (ราคาแสดงตัวอย่าง)</small><br><small>วันให้บริการ: ${e.days.map(n=>['อา.','จ.','อ.','พ.','พฤ.','ศ.','ส.'][n]).join(' / ')}</small></div>`;
 $('slots').innerHTML=valid?e.hours.map(t=>`<button type="button" class="slot" data-time="${t}" ${busy(date,t,e.name)||new Date(date+'T'+t+':00')<=new Date()?'disabled':''}>${t}${busy(date,t,e.name)?' · เต็ม':''}</button>`).join(''):'<span class="small">เลือกวันที่ผู้เชี่ยวชาญให้บริการภายใน 60 วันข้างหน้า</span>';
 $('slots').querySelectorAll('.slot:not(:disabled)').forEach(btn=>btn.onclick=()=>{$('slots').querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')});
 $('bookingHint').textContent='วันและเวลาที่ว่างคำนวณจากตารางผู้เชี่ยวชาญและการจองในเบราว์เซอร์นี้ (สาธิตเท่านั้น)';}
function list(){const active=records.filter(r=>r.status!=='ยกเลิก');modal('รายการนัดหมายสาธิต',`<p class="small">การจองในอุปกรณ์นี้เท่านั้น ไม่ใช่นัดหมายกับแพทย์จริง</p>${active.length?active.map(r=>`<div class="demo-entry"><b>${esc(r.id)}</b> · ${esc(r.date)} เวลา ${esc(r.time)}<br>${esc(r.expert)} · ${esc(r.topic)}<br><small>สถานะ: ${esc(r.status)} · รหัสยืนยัน: ${esc(r.pin)}</small><br><button class="pill" data-calendar="${esc(r.id)}">เพิ่มในปฏิทิน (.ics)</button> <button class="pill" data-cancel2="${esc(r.id)}">ยกเลิก</button></div>`).join(''):'<p>ยังไม่มีรายการจอง</p>'}`);document.querySelectorAll('[data-cancel2]').forEach(b=>b.onclick=()=>{if(confirm('ยืนยันยกเลิกนัดหมายสาธิต?')){const r=records.find(x=>x.id===b.dataset.cancel2);r.status='ยกเลิก';save();refresh();list()}});document.querySelectorAll('[data-calendar]').forEach(b=>b.onclick=()=>{const r=records.find(x=>x.id===b.dataset.calendar);const e=experts.find(x=>x.name===r.expert);const start=new Date(r.date+'T'+r.time+':00'),end=new Date(start.getTime()+e.duration*60000),fmt=d=>d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'T'+String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0')+'00';const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MindHarbor//Demo//TH','BEGIN:VEVENT','UID:'+r.id+'@mindharbor-demo.invalid','DTSTART:'+fmt(start),'DTEND:'+fmt(end),'SUMMARY:MindHarbor DEMO - '+r.expert,'DESCRIPTION:นัดหมายสาธิต ไม่ใช่การนัดหมายกับแพทย์จริง','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a'),u=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));a.href=u;a.download=r.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)})}
function book(){const e=getExpert(),date=$('date').value,time=selectedTime(),topic=document.querySelector('.topic.selected')?.dataset.topic||'ปรึกษาทั่วไป';if(!time||!date){alert('กรุณาเลือกวันและเวลาที่ยังว่าง');return}if(busy(date,time,e.name)){refresh();alert('เวลานี้ถูกจองแล้ว');return}modal('ยืนยันการจองนัดหมายสาธิต',`<p><strong>${esc(e.name)}</strong><br>${esc(date)} เวลา ${esc(time)} · ${e.duration} นาที<br>หัวข้อ: ${esc(topic)}</p><label for="bookAlias">ชื่อเล่นหรือรหัสที่ต้องการใช้ (ไม่จำเป็น)</label><input id="bookAlias" maxlength="40" placeholder="เช่น MH-Guest"/><label for="bookChannel">รูปแบบการปรึกษา</label><select id="bookChannel"><option>วิดีโอคอล (สาธิต)</option><option>พบผู้เชี่ยวชาญ (สาธิต)</option></select><label><input type="checkbox" id="bookConsent"/> รับทราบว่าแพทย์และข้อมูลทั้งหมดเป็นสมมติ ไม่มีการส่งนัดหมายจริง</label><div class="notice">ข้อมูลเก็บในเบราว์เซอร์เครื่องนี้เท่านั้น ไม่ควรใส่ข้อมูลสุขภาพจริง</div><button id="confirmRealDemo" class="pill primary" style="margin-top:12px;width:100%">ยืนยันจองคิวสาธิต</button>`);$('confirmRealDemo').onclick=()=>{if(!$('bookConsent').checked){alert('กรุณารับทราบเงื่อนไขสาธิต');return}if(busy(date,time,e.name)){refresh();alert('เวลานี้ถูกจองแล้ว');return}const id='MH-'+Date.now().toString(36).toUpperCase(),pin=String(Math.floor(100000+Math.random()*900000));records.push({id,pin,expert:e.name,date,time,topic,alias:$('bookAlias').value.trim().slice(0,40),channel:$('bookChannel').value,status:'ยืนยันในระบบสาธิต',created:new Date().toISOString()});save();refresh();modal('จองคิวสาธิตสำเร็จ',`<p>รหัสการจอง <b>${id}</b><br>รหัสยืนยัน <b>${pin}</b></p><p>${esc(e.name)} · ${esc(date)} ${esc(time)}</p><div class="notice">นี่คือการจองสาธิตในเบราว์เซอร์ ไม่ได้ส่งถึงผู้เชี่ยวชาญจริง</div><button id="openMyBookings" class="pill primary">ดูรายการและเพิ่มลงปฏิทิน</button>`);$('openMyBookings').onclick=list}}
function init(){const booking=$('booking');if(!booking)return;const select=$('expertSelect');if(!select)return;select.innerHTML=experts.map(e=>`<option value="${esc(e.name)}">${esc(e.name)} · ${esc(e.role)}</option>`).join('');const summary=document.createElement('div');summary.id='expertSummary';summary.className='expert-summary';select.after(summary);const date=$('date');date.min=localToday();date.max=plusDays(60);date.value=plusDays(1);select.onchange=refresh;date.onchange=refresh;booking.querySelector('.bookbtn').onclick=book;$('myBookingsBtn').onclick=list;document.querySelectorAll('.expert-link').forEach((a,i)=>a.addEventListener('click',()=>{select.selectedIndex=i;refresh()}));const old=$('demoBookings');if(old)old.onclick=list;const hint=booking.querySelector('.bookbtn + .small');if(hint)hint.textContent='* ระบบจองคิวนี้ใช้งานได้ในโหมดสาธิตเท่านั้น ไม่ได้เชื่อมต่อปฏิทินผู้เชี่ยวชาญจริง';refresh()}
const css=document.createElement('style');css.textContent='.expert-summary{display:flex;gap:10px;align-items:center;background:#ffffffeb;border:1px solid #d8eae5;border-radius:12px;padding:9px;margin:10px 0;font-size:12px}.expert-summary img{width:52px;height:52px;object-fit:cover;border-radius:50%}.slot:disabled{opacity:.43;cursor:not-allowed;text-decoration:line-through}.booking .demo-booking{margin-top:10px}.modal label:has(input[type=checkbox]){display:flex;gap:8px;align-items:flex-start}.modal label input[type=checkbox]{width:auto;margin:4px}';document.head.append(css);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
