/* MindHarbor offline functional DEMO. Do not enter real health or identifying information. */
(()=>{'use strict';
const KEY='mindharbor_demo_v3';
const seed={bookings:[],contacts:[],assessments:[],packageRequests:[],selectedExpert:'นพ. ธนวัฒน์ ศรีวรรณ'};
let state;try{state={...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state={...seed}};
const $=id=>document.getElementById(id), save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{alert('พื้นที่จัดเก็บข้อมูลในเบราว์เซอร์เต็มหรือถูกปิด')}};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=> 'MH-'+Math.random().toString(36).slice(2,8).toUpperCase();
const now=()=>new Date().toLocaleString('th-TH');
function modal(title,body){$('modalTitle').textContent=title;$('modalContent').innerHTML=body;$('modal').classList.add('show')}
function exportCSV(name,rows){const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function setupBooking(){const booking=$('booking');const p=document.createElement('div');p.className='demo-booking';p.innerHTML=`<label for="expertSelect">เลือกผู้เชี่ยวชาญ (ข้อมูลสมมติ)</label><select id="expertSelect" class="field"><option>นพ. ธนวัฒน์ ศรีวรรณ</option><option>ดร. กมลวรรณ จันทร์เพ็ญ</option><option>คุณธีรดา เมธากุล</option><option>คุณเอกณรงค์ พัฒนกิจ</option></select><div id="bookingHint" class="small">เลือกวันและเวลาที่ต้องการ</div><button class="pill" type="button" id="myBookingsBtn">ดูและยกเลิกการจองของฉัน</button>`;booking.querySelector('.bookbtn').before(p);$('expertSelect').value=state.selectedExpert;/* shared booking handler controls expert and date selection */$('myBookingsBtn').onclick=listBookings;updateSlots()}
function updateSlots(){const date=$('date').value,expert=$('expertSelect').value;document.querySelectorAll('.slot').forEach(el=>{const busy=state.bookings.some(b=>b.date===date&&b.expert===expert&&b.time===el.textContent.trim());el.disabled=busy;el.title=busy?'เวลานี้ถูกจองแล้ว':'';if(busy)el.classList.remove('selected')});$('bookingHint').textContent='เวลาที่จองแล้วจะไม่สามารถเลือกซ้ำสำหรับผู้เชี่ยวชาญคนเดิมได้'}
window.book=function(){const date=$('date').value, time=document.querySelector('.slot.selected:not(:disabled)')?.textContent.trim(),expert=$('expertSelect').value,topic=document.querySelector('.topic.selected')?.dataset.topic;if(!date||!time){alert('กรุณาเลือกวันและเวลาที่ยังว่าง');return}if(date<new Date().toISOString().slice(0,10)){alert('กรุณาเลือกวันในอนาคต');return}if(state.bookings.some(b=>b.date===date&&b.time===time&&b.expert===expert)){updateSlots();alert('เวลานี้ถูกจองแล้ว');return}modal('ยืนยันการจองคิวสาธิต',`<p><b>${safe(expert)}</b><br>หัวข้อ: ${safe(topic)}<br>วันที่: ${safe(date)} เวลา ${safe(time)}</p><div class="notice">ระบบสาธิต: การจองจะบันทึกในเบราว์เซอร์เครื่องนี้เท่านั้น ไม่มีการติดต่อผู้เชี่ยวชาญจริง กรุณาอย่ากรอกข้อมูลสุขภาพจริง</div><button class="pill primary" id="confirmBooking">ยืนยันการจองจำลอง</button>`);$('confirmBooking').onclick=()=>{if(state.bookings.some(b=>b.date===date&&b.time===time&&b.expert===expert)){alert('เวลานี้ไม่ว่างแล้ว');hideModal();updateSlots();return}const b={id:uid(),date,time,expert,topic,created:now()};state.bookings.push(b);save();updateSlots();renderDemo();modal('จองคิวจำลองสำเร็จ',`<p>รหัสการจอง: <b>${b.id}</b></p><p>${safe(expert)} · ${safe(date)} · ${safe(time)}</p><div class="notice">การจองนี้เป็นข้อมูลสาธิตในอุปกรณ์นี้เท่านั้น</div><button class="pill primary" id="viewMyBookings">ดูรายการจอง</button>`);$('viewMyBookings').onclick=listBookings}}
function listBookings(){modal('การจองจำลองของฉัน',state.bookings.length?state.bookings.map(b=>`<div class="demo-entry"><b>${safe(b.id)}</b> · ${safe(b.date)} ${safe(b.time)}<br>${safe(b.expert)}<br><small>${safe(b.topic)}</small><br><button class="pill" data-cancel="${b.id}">ยกเลิกการจอง</button></div>`).join(''):'<p>ยังไม่มีรายการจอง</p>');document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{if(!confirm('ยกเลิกการจองจำลองนี้?'))return;state.bookings=state.bookings.filter(x=>x.id!==b.dataset.cancel);save();updateSlots();renderDemo();listBookings()})}
window.showResult=function(){const vals=Array.from({length:qs.length},(_,i)=>answers[i]);if(vals.some(v=>v===undefined)){alert('กรุณาตอบคำถามให้ครบ');return}const total=vals.reduce((a,b,i)=>a+(i>=2?4-b:b),0);const rec={id:uid(),score:total,date:now()};state.assessments.push(rec);save();renderDemo();document.querySelector('.formcard').innerHTML=`<h3>ประเมินเสร็จแล้ว 💚</h3><p>คะแนนแบบสำรวจสาธิต <b>${total}/20</b></p><div class="notice">นี่คือแบบสำรวจที่สร้างขึ้นเพื่อสาธิตเท่านั้น ไม่ใช่เครื่องมือคัดกรองทางคลินิกหรือการวินิจฉัย คะแนนนี้ไม่ควรใช้ตัดสินภาวะสุขภาพจิต</div><p class="small">หากมีความเครียดที่รบกวนชีวิตประจำวัน ควรปรึกษาผู้เชี่ยวชาญที่ได้รับใบอนุญาต</p><button class="pill" id="restartAssess">ทำแบบประเมินอีกครั้ง</button> <a href="#booking" class="pill primary">จองคิวจำลอง</a>`;$('restartAssess').onclick=()=>{state.assessments=state.assessments.filter(a=>a.id!==rec.id);save();location.reload()}};
const oldShow=window.showModal;window.showModal=function(type){if(type==='report'){showReport();return}if(type==='login'){modal('พื้นที่สาธิต / Demo Workspace',`<p>ไม่มีบัญชีผู้ใช้จริงในต้นแบบนี้ คุณสามารถทดลองดูข้อมูลสาธิตและส่งออกข้อมูลที่เก็บในเบราว์เซอร์ได้</p><a class="pill primary" href="#demo-workspace" onclick="hideModal()">เปิด Demo Workspace</a>`);return}oldShow(type)};
window.downloadReport=function(){const n=state.assessments.length,avg=n?(state.assessments.reduce((s,x)=>s+x.score,0)/n).toFixed(1):'N/A';exportCSV('mindharbor-hr-demo.csv',[['Metric','Value','Note'],['Demo assessment count',n,'Local simulation only'],['Average demo score',n>=5?avg:'Hidden (fewer than 5)','Not clinically validated'],['Demo bookings',state.bookings.length,'Synthetic/local demo'],['Sample employee engagement',76,'Illustrative only']])};
function showReport(){const n=state.assessments.length;modal('รายงาน HR (ข้อมูลสาธิต)',`<p>จำนวนแบบประเมินจำลอง: <b>${n}</b><br>จำนวนการจองจำลอง: <b>${state.bookings.length}</b></p><div class="notice">ไม่แสดงคะแนนเฉลี่ยจากผู้ตอบน้อยกว่า 5 รายการ และไม่เปิดเผยคำตอบรายบุคคล ตัวเลขเดิมในกราฟบนหน้าเว็บเป็นข้อมูลสมมติประกอบการนำเสนอ</div><button class="pill primary" onclick="downloadReport()">ดาวน์โหลดรายงาน CSV</button>`)}
function setupContact(){const f=$('contactForm');const newF=f.cloneNode(true);f.replaceWith(newF);newF.addEventListener('submit',e=>{e.preventDefault();if(!newF.reportValidity())return;const name=$('contactName').value.trim(),email=$('contactEmail').value.trim(),message=$('contactMessage').value.trim();if(!name||!email||!message)return;const rec={id:uid(),name,email,message,date:now(),status:'รอดำเนินการ (จำลอง)'};state.contacts.push(rec);save();newF.reset();$('contactResult').textContent=`บันทึกข้อความจำลองแล้ว รหัส ${rec.id} (ยังไม่มีการส่งอีเมลจริง)`;renderDemo()})}
function setupExtras(){document.querySelectorAll('.expert-link').forEach((a,i)=>a.addEventListener('click',()=>{const sel=$('expertSelect');sel.selectedIndex=i;state.selectedExpert=sel.value;save()}));document.querySelectorAll('#pricing .cta-link').forEach((a,i)=>a.addEventListener('click',()=>{state.packageRequests.push({id:uid(),package:['Starter','Professional','Enterprise'][i]||'Enterprise',date:now()});save();renderDemo()}));const s=document.createElement('section');s.id='demo-workspace';s.className='extended demo-workspace';s.innerHTML=`<div class="section-head"><div><div class="eyebrow2">INTERACTIVE OFFLINE DEMO</div><h2>พื้นที่จัดการข้อมูลจำลอง</h2><p class="lead">ทดลองใช้งานระบบครบวงจรในเบราว์เซอร์ของคุณ ไม่ต้องสร้างบัญชีและไม่ส่งข้อมูลไปยังเซิร์ฟเวอร์</p></div><span class="tag">DEMO ONLY</span></div><div class="demo-stats" id="demoStats"></div><div class="demo-actions"><button class="pill primary" id="demoBookings">ดู / ยกเลิกการจอง</button><button class="pill" id="demoContacts">ข้อความติดต่อจำลอง</button><button class="pill" id="demoPackages">แพ็กเกจที่สนใจ</button><button class="pill" id="demoReport">รายงาน HR</button><button class="pill" id="demoExport">ส่งออกข้อมูลของฉัน (JSON)</button><button class="pill danger" id="demoClear">ล้างข้อมูลจำลองทั้งหมด</button></div><div class="notice">ความเป็นส่วนตัว: ข้อมูลจำลองบันทึกใน localStorage ของเบราว์เซอร์เครื่องนี้ ไม่ใช่ Zero-Knowledge หรือระบบรักษาความปลอดภัยสำหรับข้อมูลสุขภาพจริง ห้ามใช้ข้อมูลส่วนบุคคลหรือข้อมูลสุขภาพจริงในการทดลอง</div>`;$('contact').before(s);$('demoBookings').onclick=listBookings;$('demoContacts').onclick=()=>modal('ข้อความติดต่อจำลอง',state.contacts.length?state.contacts.map(c=>`<div class="demo-entry"><b>${safe(c.id)}</b> · ${safe(c.date)}<br>${safe(c.name)} · ${safe(c.email)}<br>${safe(c.message)}<br><small>${safe(c.status)}</small></div>`).join(''):'<p>ยังไม่มีข้อความ</p>');$('demoPackages').onclick=()=>modal('ความสนใจแพ็กเกจ',state.packageRequests.length?state.packageRequests.map(x=>`<p>${safe(x.package)} · ${safe(x.date)} (${safe(x.id)})</p>`).join(''):'<p>ยังไม่มีข้อมูล</p>');$('demoReport').onclick=showReport;$('demoExport').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=u;a.download='mindharbor-my-demo-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('demoClear').onclick=()=>{if(confirm('ลบข้อมูลจำลองทั้งหมดในเบราว์เซอร์เครื่องนี้?')){localStorage.removeItem(KEY);state=structuredClone(seed);updateSlots();renderDemo();alert('ล้างข้อมูลจำลองเรียบร้อยแล้ว')}};renderDemo()}
function renderDemo(){if(!$('demoStats'))return;$('demoStats').innerHTML=[['แบบประเมินจำลอง',state.assessments.length],['การจองจำลอง',state.bookings.length],['ข้อความติดต่อ',state.contacts.length],['สนใจแพ็กเกจ',state.packageRequests.length]].map(([a,b])=>`<div class="demo-stat"><strong>${b}</strong><span>${a}</span></div>`).join('')}
setupBooking();setupContact();setupExtras();
})();
