/* MindHarbor fictional-expert shared booking demo. Node.js 18+; no dependencies. */
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,db=path.join(root,'demo-bookings.json');
const experts=[
{id:'psychiatrist',name:'นพ. ธนวัฒน์ ศรีวรรณ',role:'จิตแพทย์ (สมมติ)',days:[1,3,5],hours:['09:00','10:00','11:00','14:00'],duration:50,fee:1800,img:'assets/psychiatrist.png'},
{id:'psychologist',name:'ดร. กมลวรรณ จันทร์เพ็ญ',role:'นักจิตวิทยาคลินิก (สมมติ)',days:[2,4,6],hours:['10:00','11:00','13:00','15:00'],duration:50,fee:1200,img:'assets/psychologist.png'},
{id:'wellbeing',name:'คุณธีรดา เมธากุล',role:'ผู้เชี่ยวชาญสุขภาวะองค์กร (สมมติ)',days:[1,2,4,5],hours:['09:00','11:00','13:00','16:00'],duration:60,fee:1500,img:'assets/wellbeing.png'},
{id:'counselor',name:'คุณเอกณรงค์ พัฒนกิจ',role:'นักจิตวิทยาการปรึกษา (สมมติ)',days:[1,3,4,6],hours:['09:00','10:00','14:00','15:00'],duration:50,fee:1100,img:'assets/counselor.png'}];
let crm={};let automation=[];try{crm=JSON.parse(fs.readFileSync(path.join(root,'demo-crm.json'),'utf8'))}catch{};try{automation=JSON.parse(fs.readFileSync(path.join(root,'demo-automation.json'),'utf8'))}catch{};let bookings=[];try{bookings=JSON.parse(fs.readFileSync(db,'utf8'))}catch{}
const PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'127.0.0.1';
const reply=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'});
function allowed(ex,date,time){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return false;const d=new Date(date+'T12:00:00+07:00');if(!Number.isFinite(d.getTime())||d.toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'})!==date)return false;const diff=(Date.parse(date+'T00:00:00+07:00')-Date.parse(today()+'T00:00:00+07:00'))/86400000;return diff>=0&&diff<=60&&ex.days.includes(d.getUTCDay())&&ex.hours.includes(time)&&Date.parse(date+'T'+time+':00+07:00')>Date.now()}
function persistCRM(){fs.writeFileSync(path.join(root,'demo-crm.json'),JSON.stringify(crm,null,2),{mode:0o600})}function emitWorkflow(event,rec){const now=new Date().toISOString();automation.push({id:crypto.randomUUID(),event,booking:rec.id,at:now,actions:[{type:'email',recipient:'ลูกค้า (จำลอง)',status:'simulated',message:event==='booking.created'?'ยืนยันการจอง '+rec.id:'ยืนยันการยกเลิก '+rec.id},{type:'admin_notification',recipient:'แอดมิน (จำลอง)',status:'simulated',message:event+' / '+rec.id}]});fs.writeFileSync(path.join(root,'demo-automation.json'),JSON.stringify(automation,null,2),{mode:0o600})}function persist(){const tmp=db+'.tmp';fs.writeFileSync(tmp,JSON.stringify(bookings,null,2),{mode:0o600});fs.renameSync(tmp,db)}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',b=>{s+=b;if(s.length>10000){reject(Error('too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch{reject(Error('invalid json'))}});req.on('error',reject)})}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/experts'&&req.method==='GET')return reply(res,200,{experts});
if(u.pathname==='/api/slots'&&req.method==='GET'){const ex=experts.find(x=>x.id===u.searchParams.get('expert')),date=u.searchParams.get('date')||'';if(!ex)return reply(res,400,{error:'Invalid expert'});return reply(res,200,{date,expert:ex.id,slots:ex.hours.map(time=>({time,available:allowed(ex,date,time)&&!bookings.some(b=>b.expert===ex.id&&b.date===date&&b.time===time&&b.status==='confirmed')}))})}
if(u.pathname==='/api/bookings'&&req.method==='POST'){const b=await body(req),ex=experts.find(x=>x.id===b.expert);if(!ex||!allowed(ex,b.date,b.time))return reply(res,400,{error:'เลือกวันเวลาที่เปิดให้บริการภายใน 60 วัน'});if(bookings.some(x=>x.expert===ex.id&&x.date===b.date&&x.time===b.time&&x.status==='confirmed'))return reply(res,409,{error:'เวลานี้มีผู้จองแล้ว กรุณาเลือกเวลาอื่น'});const id='MH-'+crypto.randomBytes(5).toString('hex').toUpperCase(),token=crypto.randomBytes(16).toString('hex');const rec={id,token,expert:ex.id,date:b.date,time:b.time,topic:String(b.topic||'ปรึกษาทั่วไป').slice(0,80),alias:String(b.alias||'').slice(0,40),channel:['วิดีโอคอล (สาธิต)','พบผู้เชี่ยวชาญ (สาธิต)'].includes(b.channel)?b.channel:'วิดีโอคอล (สาธิต)',status:'confirmed',created:new Date().toISOString()};bookings.push(rec);persist();emitWorkflow('booking.created',rec);return reply(res,201,{booking:{...rec,expertName:ex.name}})}
if(u.pathname==='/api/my-bookings'&&req.method==='POST'){const b=await body(req),ids=Array.isArray(b.keys)?b.keys.slice(0,100):[];return reply(res,200,{bookings:bookings.filter(x=>ids.some(k=>k.id===x.id&&k.token===x.token)).map(({token,...x})=>({...x,expertName:experts.find(e=>e.id===x.expert)?.name}))})}
if(u.pathname==='/api/cancel'&&req.method==='POST'){const b=await body(req),rec=bookings.find(x=>x.id===b.id&&x.token===b.token);if(!rec)return reply(res,404,{error:'ไม่พบรายการหรือรหัสไม่ถูกต้อง'});if(rec.status!=='confirmed')return reply(res,409,{error:'รายการนี้ถูกยกเลิกแล้ว'});rec.status='cancelled';persist();emitWorkflow('booking.cancelled',rec);return reply(res,200,{ok:true})}
if(u.pathname==='/api/crm'&&req.method==='POST'){const b=await body(req),token=String(b.token||'');if(!/^[a-f0-9]{32}$/.test(token))return reply(res,400,{error:'Invalid demo token'});if(!crm[token])crm[token]={alias:'Guest',preferredExpert:'',preferredChannel:'วิดีโอคอล (สาธิต)',reminders:true,marketing:false,points:0,lastActivity:'',created:new Date().toISOString()};if(b.action==='save'){crm[token].alias=String(b.alias||'Guest').slice(0,40);crm[token].preferredExpert=experts.some(e=>e.id===b.preferredExpert)?b.preferredExpert:'';crm[token].preferredChannel=['วิดีโอคอล (สาธิต)','พบผู้เชี่ยวชาญ (สาธิต)'].includes(b.preferredChannel)?b.preferredChannel:'วิดีโอคอล (สาธิต)';crm[token].reminders=b.reminders===true;crm[token].marketing=b.marketing===true}else if(b.action==='learn'){const day=today();if(crm[token].lastActivity!==day){crm[token].points+=10;crm[token].lastActivity=day}}persistCRM();return reply(res,200,{profile:crm[token],rewards:[{points:30,name:'ดาวน์โหลดสมุดบันทึกสุขภาวะ (สาธิต)'},{points:70,name:'เข้าร่วมเวิร์กช็อปทั่วไป (สาธิต)'}]})}
if(u.pathname==='/api/workflow'&&req.method==='POST'){const b=await body(req),keys=Array.isArray(b.keys)?b.keys.slice(0,100):[];return reply(res,200,{events:automation.filter(x=>keys.some(k=>k.id===x.booking&&bookings.some(y=>y.id===k.id&&y.token===k.token))).slice(-30).reverse()})}
if(u.pathname.startsWith('/api/'))return reply(res,404,{error:'Unknown endpoint'});
if(req.method!=='GET')return reply(res,405,{error:'Method not allowed'});let p=decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname);const full=path.resolve(root,'.'+p);if(!full.startsWith(root+path.sep)||['demo-bookings.json','demo-crm.json','demo-automation.json','server.js','README.txt'].includes(path.basename(full)))return reply(res,403,{error:'Forbidden'});const stat=fs.statSync(full);if(!stat.isFile())throw Error('not file');res.writeHead(200,{'Content-Type':mime[path.extname(full)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});fs.createReadStream(full).pipe(res)
}catch(e){reply(res,e.code==='ENOENT'?404:400,{error:e.code==='ENOENT'?'Not found':'Request failed'})}}).listen(PORT,HOST,()=>console.log(`MindHarbor demo: http://${HOST}:${PORT} (fictional experts only)`));
